1485188217929	addons.update-checker	WARN	Update manifest for {972ce4c6-7e08-4474-a285-3208198ce6fd} did not contain an updates property
1485188217991	addons.update-checker	WARN	Update manifest for e10srollout@mozilla.org did not contain an updates property
1485188218009	addons.update-checker	WARN	Update manifest for webcompat@mozilla.org did not contain an updates property
1485188218019	addons.update-checker	WARN	Update manifest for firefox@getpocket.com did not contain an updates property
1485188218044	addons.update-checker	WARN	Update manifest for aushelper@mozilla.org did not contain an updates property
/var/lib/dpkg/lock: 

(/usr/lib/firefox/plugin-container:2726): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox/plugin-container:2726): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox/plugin-container:2726): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox/plugin-container:2726): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

** (update-notifier:1965): WARNING **: log file empty (logrotate?) /var/log/dpkg.log

** (update-notifier:1965): WARNING **: log file empty (logrotate?) /var/log/apt/term.log
2017-01-23 11:44:44,357 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2017-01-23 11:44:45,277 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Geoclue.Master was not provided by any .service files'
2017-01-23 11:44:45,557 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2017-01-23 11:44:45,568 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2017-01-23 11:44:45,783 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2017-01-23 11:44:46,781 - softwarecenter.db.update - WARNING - failed to load file /var/lib/apt-xapian-index/cataloged_times.p: 
2017-01-23 11:44:47,970 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
/usr/bin/software-center:184: Warning: Source ID 112 was not found when attempting to remove it
  Gtk.main()
2017-01-23 11:44:50,059 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2017-01-23 11:44:50,059 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')
/usr/bin/software-center:184: Warning: Source ID 68 was not found when attempting to remove it
  Gtk.main()
2017-01-23 11:44:50,284 - softwarecenter.db.update - WARNING - failed to load file /var/lib/apt-xapian-index/cataloged_times.p: 
2017-01-23 11:44:52,658 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Geoclue.Master was not provided by any .service files'
/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py:535: Warning: Source ID 20 was not found when attempting to remove it
  return super(MainContext, self).iteration(may_block)
2017-01-23 11:44:55,241 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0

(Thunar:1908): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

(Thunar:1908): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

(Thunar:1908): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

(Thunar:1908): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

(xfce4-terminal:6706): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

(firefox:2256): Gtk-CRITICAL **: gtk_clipboard_set_with_data: assertion 'targets != NULL' failed
[libprotobuf ERROR /build/firefox-motZyY/firefox-50.1.0+build2/toolkit/components/protobuf/src/google/protobuf/message_lite.cc:123] Can't parse message of type "safe_browsing.ClientDownloadResponse" because it is missing required fields: (cannot determine missing fields for lite message)
2017-01-23 12:17:33,064 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2017-01-23 12:17:33,215 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Geoclue.Master was not provided by any .service files'
2017-01-23 12:17:33,509 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2017-01-23 12:17:33,511 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2017-01-23 12:17:33,632 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2017-01-23 12:17:35,109 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2017-01-23 12:17:35,111 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')
/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py:535: Warning: Source ID 55 was not found when attempting to remove it
  return super(MainContext, self).iteration(may_block)
2017-01-23 12:17:35,618 - softwarecenter.db.update - WARNING - failed to load file /var/lib/apt-xapian-index/cataloged_times.p: 
2017-01-23 12:17:37,141 - softwarecenter.db.update - WARNING - failed to load file /var/lib/apt-xapian-index/cataloged_times.p: 
2017-01-23 12:17:37,397 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py:535: Warning: Source ID 107 was not found when attempting to remove it
  return super(MainContext, self).iteration(may_block)
2017-01-23 12:17:42,238 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "code"}']'
2017-01-23 12:17:42,249 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:404: {'status': '404', 'content-length': '53', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'HIT from papeda.canonical.com', 'age': '12', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache', 'etag': '"486a668598caf1deb93376714b0aa688"', 'cache-control': 'max-age=300', 'date': 'Mon, 23 Jan 2017 17:17:30 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128'}
'
2017-01-23 12:17:42,249 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:404: {'status': '404', 'content-length': '53', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'HIT from papeda.canonical.com', 'age': '12', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache', 'etag': '"486a668598caf1deb93376714b0aa688"', 'cache-control': 'max-age=300', 'date': 'Mon, 23 Jan 2017 17:17:30 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128'}

2017-01-23 12:17:42,249 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:404: {'status': '404', 'content-length': '53', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'HIT from papeda.canonical.com', 'age': '12', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache', 'etag': '"486a668598caf1deb93376714b0aa688"', 'cache-control': 'max-age=300', 'date': 'Mon, 23 Jan 2017 17:17:30 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128'}

2017-01-23 12:17:42,524 - softwarecenter.db.pkginfo_impl.aptcache - ERROR - simulate failed
None
/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py:535: Warning: Source ID 267 was not found when attempting to remove it
  return super(MainContext, self).iteration(may_block)
2017-01-23 12:17:42,883 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Geoclue.Master was not provided by any .service files'
/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py:535: Warning: Source ID 20 was not found when attempting to remove it
  return super(MainContext, self).iteration(may_block)
/usr/bin/software-center:184: Warning: Source ID 362 was not found when attempting to remove it
  Gtk.main()
2017-01-23 12:17:47,188 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 145 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 5399 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 6592 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 7586 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 8575 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 9562 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 12705 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 13994 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 14888 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/backend/installbackend_impl/aptd.py:764: Warning: Source ID 4999 was not found when attempting to remove it
  GLib.source_remove(self._progress_signal)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 16350 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 17178 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 18367 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 19673 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 21091 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 21390 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 22013 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 22761 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/backend/installbackend_impl/aptd.py:764: Warning: Source ID 9706 was not found when attempting to remove it
  GLib.source_remove(self._progress_signal)
/usr/share/software-center/softwarecenter/ui/gtk3/models/pendingstore.py:64: Warning: Source ID 9707 was not found when attempting to remove it
  GLib.source_remove(sig)
/usr/share/software-center/softwarecenter/ui/gtk3/models/pendingstore.py:64: Warning: Source ID 9708 was not found when attempting to remove it
  GLib.source_remove(sig)
/usr/share/software-center/softwarecenter/ui/gtk3/models/pendingstore.py:64: Warning: Source ID 9709 was not found when attempting to remove it
  GLib.source_remove(sig)
/usr/share/software-center/softwarecenter/ui/gtk3/models/pendingstore.py:64: Warning: Source ID 9710 was not found when attempting to remove it
  GLib.source_remove(sig)
2017-01-23 12:22:10,020 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 23556 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 24238 was not found when attempting to remove it
  GLib.source_remove(self._timeout)

(software-center:10798): Gtk-CRITICAL **: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed
/usr/share/software-center/softwarecenter/ui/gtk3/widgets/exhibits.py:404: Warning: Source ID 24786 was not found when attempting to remove it
  GLib.source_remove(self._timeout)
pci id for fd 15: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
thunar-volman: Unsupported USB device type.
thunar-volman: Unsupported USB device type.
clang: error: no input files

(xfce4-terminal:15200): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
/var/lib/dpkg/lock: 

(/usr/lib/firefox/plugin-container:20431): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox/plugin-container:20431): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox/plugin-container:20431): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox/plugin-container:20431): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

###!!! [Child][MessageChannel] Error: (msgtype=0x4A00C2,name=PContent::Msg_ConsoleMessage) Channel closing: too late to send/recv, messages will be lost

pci id for fd 7: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo

(firefox:2256): Gtk-CRITICAL **: gtk_clipboard_set_with_data: assertion 'targets != NULL' failed
pci id for fd 15: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

(xfce4-terminal:21172): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

(xfce4-terminal:21229): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

(xfce4-terminal:21296): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

(Thunar:1908): Gdk-CRITICAL **: IA__gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
pci id for fd 15: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
pci id for fd 15: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
